### ISSUE TITLE
Ban? 

### ISSUE THREAD

**Issue by Mantis1980** [Bulli77/CSGO-OW-2022---FreeStylers-BOT#1]
I make overwatch approximately 6 months ago and I get now ban it’s can be fro this ? I don’t think but I just ask. 😅 and you make upload to cs2?

**Comment by CodeBerserkers888** [comment]
Surely not :) Bans have been handed out recently for using wallhacks, but many people I know who use this program haven't been banned. However, I do know that 6 months ago it wasn't working because it was missing an additional library. As for whether it will work for CS2, I'm not sure, we'll have to see what Valve comes up with.
